spring:
  data:
    mongodb:
      host: mongodb.datajud.kinghost.net
      database: datajud01
      username: datajud01
      password: datajud_pwd
  cache:
    jcache:
      config: classpath:ehcache.xml
logging:
  level:
    root: warn
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: warn
sgt-client:
  url: https://www.cnj.jus.br/sgt/sgt_ws.php
  enable-logging: true
  timeout: 60000
  cache-ttl: 86400
windowSize: 10
