spring:
  data:
    mongodb:
      host: mongodb.datajud.kinghost.net
      database: datajud01
      username: datajud01
      password: datajud_pwd
logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG




