server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/inova.p12
    key-password: changeit
    key-alias: inova
    enabled: true
spring:
  data:
    mongodb:
      host: mongodb.datajud.kinghost.net
      database: datajud01
      username: datajud01
      password: datajud_pwd
  cache:
    jcache:
      config: classpath:ehcache.xml
logging:
  level:
    root: info
sgt-client:
  url: https://www.cnj.jus.br/sgt/sgt_ws.php
  enable-logging: true
  timeout: 60000
  cache-ttl: 86400
windowSize: 10

